[build]
  command = "make build"
  functions = "functions"
  publish = "public"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/tommycwu/okta-go-event-hook"
